export const PERMISSIONS = {
  ACCESO_TOTAL: 'ACCESO_TOTAL',
  VER_PANEL: 'VER_PANEL',
  GESTION_EMPLEADOS: 'GESTION_EMPLEADOS',
  GESTION_ROLES: 'GESTION_ROLES',
  GESTION_POS: 'GESTION_POS',
  GESTION_MESAS: 'GESTION_MESAS',
  GESTION_PEDIDOS: 'GESTION_PEDIDOS',
  GESTION_PRECUENTA: 'GESTION_PRECUENTA',
  GESTION_CAJA: 'GESTION_CAJA',
  GESTION_COCINA: 'GESTION_COCINA',
  GESTION_VENTAS: 'GESTION_VENTAS',
  GESTION_COMPRAS: 'GESTION_COMPRAS',
  GESTION_INVENTARIO: 'GESTION_INVENTARIO',
  GESTION_PRODUCTOS: 'GESTION_PRODUCTOS',
  GESTION_RECETAS: 'GESTION_RECETAS',
  GESTION_REPORTES: 'GESTION_REPORTES',
  GESTION_CONFIGURACION: 'GESTION_CONFIGURACION',
  GESTION_AUDITORIA: 'GESTION_AUDITORIA',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
