export const PERMISSIONS = {
  VER_DASHBOARD: 'VER_DASHBOARD',
  VER_VENTAS: 'VER_VENTAS',
  VER_REPORTES: 'VER_REPORTES',
  VER_INVENTARIO: 'VER_INVENTARIO',
  USAR_POS: 'USAR_POS',
  CAJA_GERENTE: 'CAJA_GERENTE',
  CAJA_PERSONAL: 'CAJA_PERSONAL',
  ADMIN_USUARIOS: 'ADMIN_USUARIOS',
  ADMIN_ROLES: 'ADMIN_ROLES',
  VER_AUDITORIA: 'VER_AUDITORIA',
  ADMIN_CONFIG: 'ADMIN_CONFIG'
};
